# TCL File Generated by Component Editor 19.1
# Wed Apr 08 21:22:19 PKT 2020
# DO NOT MODIFY


# 
# PeStream "Matrix Multiplier 5x5 16bit" v1.0
#  2020.04.08.21:22:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module PeStream
# 
set_module_property DESCRIPTION ""
set_module_property NAME PeStream
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Matrix Multiplier 5x5 16bit"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL PeStream
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PeStream.v VERILOG PATH PeStream.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL PeStream
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PeStream.v VERILOG PATH PeStream.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point streamA
# 
add_interface streamA avalon_streaming end
set_interface_property streamA associatedClock clock
set_interface_property streamA associatedReset reset
set_interface_property streamA dataBitsPerSymbol 8
set_interface_property streamA errorDescriptor ""
set_interface_property streamA firstSymbolInHighOrderBits true
set_interface_property streamA maxChannel 0
set_interface_property streamA readyLatency 0
set_interface_property streamA ENABLED true
set_interface_property streamA EXPORT_OF ""
set_interface_property streamA PORT_NAME_MAP ""
set_interface_property streamA CMSIS_SVD_VARIABLES ""
set_interface_property streamA SVD_ADDRESS_GROUP ""

add_interface_port streamA streamA_payload data Input 16
add_interface_port streamA streamA_ready ready Output 1
add_interface_port streamA streamA_valid valid Input 1


# 
# connection point streamB
# 
add_interface streamB avalon_streaming end
set_interface_property streamB associatedClock clock
set_interface_property streamB associatedReset reset
set_interface_property streamB dataBitsPerSymbol 8
set_interface_property streamB errorDescriptor ""
set_interface_property streamB firstSymbolInHighOrderBits true
set_interface_property streamB maxChannel 0
set_interface_property streamB readyLatency 0
set_interface_property streamB ENABLED true
set_interface_property streamB EXPORT_OF ""
set_interface_property streamB PORT_NAME_MAP ""
set_interface_property streamB CMSIS_SVD_VARIABLES ""
set_interface_property streamB SVD_ADDRESS_GROUP ""

add_interface_port streamB streamB_payload data Input 16
add_interface_port streamB streamB_ready ready Output 1
add_interface_port streamB streamB_valid valid Input 1


# 
# connection point streamR
# 
add_interface streamR avalon_streaming start
set_interface_property streamR associatedClock clock
set_interface_property streamR associatedReset reset
set_interface_property streamR dataBitsPerSymbol 8
set_interface_property streamR errorDescriptor ""
set_interface_property streamR firstSymbolInHighOrderBits true
set_interface_property streamR maxChannel 0
set_interface_property streamR readyLatency 0
set_interface_property streamR ENABLED true
set_interface_property streamR EXPORT_OF ""
set_interface_property streamR PORT_NAME_MAP ""
set_interface_property streamR CMSIS_SVD_VARIABLES ""
set_interface_property streamR SVD_ADDRESS_GROUP ""

add_interface_port streamR streamR_payload data Output 32
add_interface_port streamR streamR_ready ready Input 1
add_interface_port streamR streamR_valid valid Output 1

